# Generated by Django 5.1.1 on 2024-09-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id_tarefa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=55)),
                ('descricao', models.EmailField(max_length=500)),
                ('status', models.TextField(max_length=100)),
            ],
        ),
    ]
